CREATE DATABASE oms;
USE oms;
CREATE TABLE USER_DETAILS(
					USER_ID INT NOT NULL auto_increment,
					USER_NAME varchar(255),
					LOGIN_ID varchar(255),
                    CONTACT_NUMBER varchar(255),
                    USER_PASS VARCHAR(300),
                    IS_ACTIVE_USER bool,
                    primary key(USER_ID)
                    );
#SELECT * FROM USER_DETAILS;
CREATE TABLE CUSTOMER_DETAILS(CUSTOMER_ID INT NOT NULL auto_increment,
CUSTOMER_NAME VARCHAR(255),
CUSTOMER_EMAIL VARCHAR(255),
CUSTOMER_ADDRESS VARCHAR(400),
CREATED_BY VARCHAR(255),
CREATED_DATE TIMESTAMP,
MODIFIED_BY VARCHAR(255),
MODIFIED_DATE TIMESTAMP,
primary key(CUSTOMER_ID)
);

CREATE TABLE ORDER_MANAGER (
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    PO_NUMBER VARCHAR(255),
    ORDER_DATE TIMESTAMP,
    CUSTOMER_ID INT,
    CUSTOMER_PART_NO VARCHAR(255),
    MFG_ITEM_NO VARCHAR(255),
    ITEM_DETAILS VARCHAR(700),
    MAKER VARCHAR(255),
    PRICE FLOAT(10 , 5 ),
    PO_QTY INT NOT NULL,
    CUSTOMER_REQ_DATE TIMESTAMP,
    SUPPLIED_QTY INT NOT NULL,
    PENDING_QTY INT NOT NULL,
    ESPL_PO_OR_EBIS_NO VARCHAR(255),
    SUPPLIER_DELIVERY_DATE TIMESTAMP,
    INVOICE_NO VARCHAR(255),
    END_CUST_BILL_DATE TIMESTAMP,
    POV FLOAT(10 , 5 ),
    REMARKS VARCHAR(100),
    PO_IMAGE VARCHAR(100),
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATE TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER_DETAILS (CUSTOMER_ID)
);
#ALTER TABLE USER_DETAILS ADD USER_PASS VARCHAR(300) AFTER LOGIN_ID;

select * from OMS.USER_DETAILS;
